### ISSUE TITLE
enduranceRemainLifePercent exceeds 100

### ISSUE THREAD

**Issue by mavik1** [Ognian/sdmon#2]
With some Apacer SD cards I am reading enduranceRemainLifePercent values that exceed 100. What does a remaining life of above 100 percent mean?

**Comment by Ognian** [comment]
I haven't found any documentation about this, but I can imagine that some new sd cards have more spare blocks than others and that the predefined count is an average value, so new cards could have values slightly above or below 100%. As long as the % value decreases everything should be ok.

**Comment by Ognian** [comment]
I had now the same case with one of my cards:
```
sudo ./sdmon /dev/mmcblk0
{
"version": "v0.3.2-dirty (a743eff)",
"date": "2022-04-14T13:56:07.000Z",
"device":"/dev/mmcblk0",
"read_via_cmd56_arg_1":"read successful but signature 0xff 0xff"
"idata.response[]":"0x900 0x00 0x00 0x00",
"flashId": ["0x98","0xde","0x94","0x93","0x76","0x51","0x08","0x04","0x04"],
"icVersion": ["0x20","0x12"],
"fwVersion": [82,105],
"ceNumber": "0x04",
"spareBlockCount": 45,
"initialBadBlockCount": 77,
"goodBlockRatePercent": 98.20,
"totalEraseCount": 13807590,
"enduranceRemainLifePercentBytes": ["0xb0","0xf4"],
"enduranceRemainLifePercentNumber": 45300,
"enduranceRemainLifePercent": 453.00,
"avgEraseCount": 13590,
"minEraseCount": 3,
"maxEraseCount": 13665,
"powerUpCount": 208,
"abnormalPowerOffCount": 0,
"totalRefreshCount": 2877,
"productMarker": ["0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"],
"laterBadBlockCount": 0,
"success":true
}
```
I checked the same card with the "Apacer SD Smart" App (under Windows) and got exactly the same result:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1231174/163408077-15e12dcf-d9cf-49ed-b9df-63ccb0f289c0.png">

So it looks like this is indeed what the card reports...

**Comment by mavik1** [comment]
It looks like the card is reporting `enduranceRemainLifePercentNumber` as `avgEraseCount/3000*100*100` rather than `(1-avgEraseCount/3000)*100*100` which I think would give the remaining lifetime. As far as I know, the endurance for the flash on this card is 3000 read/write cycles.
