### ISSUE TITLE
Not found errors? Sandisk Raspbian Buster

### ISSUE THREAD

**Issue by glynhudson** [Ognian/sdmon#4]
Hi, I'm testing in a SanDisk industrial card (SDSDQAF3-016G-I) on a RaspberryPi running Raspbian Buster. I've tried with and without the `-s`  parameter, I keep getting the same `not found` errors and lots of characters. Any ideas what I'm missing? 

I've tested both the stable and development versions. 

Very cool project BTW! 

```
sudo ./sdmon -s /dev/mmcblk0
./sdmon: 1: ./sdmon: ELF�T@@h�@8@@@����8�8�A8�A�p: not found
./sdmon: 1: ./sdmon: ���!: not found
./sdmon: 1: ./sdmon: ���!: not found
./sdmon: 1: ./sdmon: bD9@5����: not found
./sdmon: 1: ./sdmon: ���İð����G���c�G��G�A�@��: not found
./sdmon: 2: ./sdmon: �@���R�
                            @��: not found
./sdmon: 3: ./sdmon: ��3��R�: not found
./sdmon: 3: ./sdmon: ����?���R�S�@�R�W�: not found
./sdmon: 1: ./sdmon: �R: not found
./sdmon: 2: ./sdmon: ��{���������G�@��?����/��Ñ: not found
./sdmon: 3: ./sdmon: ����@���R�: not found
./sdmon: 4: ./sdmon: �: not found
./sdmon: 4: ./sdmon: ����?���R�S�@�R�W�: not found
./sdmon: 4: ./sdmon: ��Ñ��: not found
./sdmon: 6: ./sdmon: ��Ñ���R: not found
./sdmon: 4: ./sdmon: Syntax error: Unterminated quoted string
```

**Comment by glynhudson** [comment]
Update, I've now compiled it myself on the RasPi and I'm getting a much better responce, but it's still not reading from the SanDisk card:

`
```
git clone https://github.com/Ognian/sdmon
cd sdmon/src
make
```

```
$~/sdmon/src $ sudo ./sdmon  /dev/mmcblk0
{
"version": "",
"date": "2022-04-08T02:29:52.000Z",
"device":"/dev/mmcblk0",
"idata.response[]":"0x900 0x00 0x00 0x00",
"error2":"2nd CMD56 CALL FAILED: Connection timed out"
}
$ ~/sdmon/src $ sudo ./sdmon -s  /dev/mmcblk0
{
"version": "",
"date": "2022-04-08T02:30:34.000Z",
"usage":"wrong argument count"
}
````

**Comment by Ognian** [comment]
@glynhudson I'm sorry it is my fault. I'm struggling the last 2 days with the build and release process of github actions...
I have to constantly push new versions ( although they are not ready!) to test the output of the CI process...
Is your raspbian buster version 32bit or 64bit? The few working builds where all 64bit and had not the SanDisk support included...
Please give me some more hours (days?) to fix this...

**Comment by glynhudson** [comment]
Ah ok, no worries! It's a 32-bit rasPi OS I'm testing on. I will wait, not rush. This is such a cool project :+1:

**Comment by wjcroft** [comment]
This is all fixed with the source in the zip on the Pi Forum thread. Glyn has already downloaded it and rebuilt. The issue above is because the SanDisk mods are not yet in this Github repo. Only in the zip on Pi Forum.

https://forums.raspberrypi.com/viewtopic.php?p=1988851

**Comment by Ognian** [comment]
I have now added the SanDisk way into the code.
A Development release is build and available.
on 32bit raspberry pi os you can install it via
```
curl -L https://github.com/Ognian/sdmon/releases/download/latest/sdmon-armv7.tar.gz | tar zxf - 
```
on 64 bit raspberry pi os use
```
curl -L https://github.com/Ognian/sdmon/releases/download/latest/sdmon-arm64.tar.gz | tar zxf - 
```
sdmon needs no command line flags, it first tries the SanDisk way. If there is a signature different from 0xffff or 0x0000 it prints the info. SanDisk: true is set if it is a SanDisk signature, so that you can be sure that the info is correct. If signature was 0xffff or 0x0000 the APACER way is tried.

I have tested with the APACER cards where it works. I don't have SanDisk Industrial Cards to test.
@glynhudson please could you test the 32 bit version with SanDisk and paste here the result so that I can put it as an example in the read.me
@wjcroft please could you test the 64bit version too and also paste the output

**Comment by wjcroft** [comment]
Ognian, thanks.

However you did not start from the latest zip I posted on the Pi Forum yesterday. It contains some string termination fixes that are needed. Otherwise depending on the 512 bytes returned, the manufacture date and product string can contain junk bytes. Here is the code section:

```
  strncpy(tmpstr, (char *)&data_in[2], 6);
  tmpstr[6] = 0;
  printf("\"manufactureYYMMDD\": \"%s\",\n", tmpstr);
  printf("\"healthStatusPercentUsed\": %d,\n", data_in[8]);
  printf("\"featureRevision\": \"0x%x\",\n", data_in[11]);
  printf("\"generationIdentifier\": %d,\n", data_in[14]);
  strncpy(tmpstr, (char *)&data_in[49], 32);
  tmpstr[32] = 0;
  printf("\"productString\": \"%s\",\n", tmpstr);
```

**Comment by Ognian** [comment]
OK, I’ve added this too now…
Do you have the part number of these SanDisk Cards? I’ve searched but was not sure if I found the correct ones…


DDI Ognian Tschakalov


OGI-IT
1130 Wien, Fasangartengasse 15
+43 699 10160670
+43 1 9835922
***@***.*** ***@***.***>
https://www.ogi-it.com <http://www.ogi-it.com/>
Firmensitz und Handelsgericht: Wien, FN: 287660 F, UID ATU 63092058

**Comment by wjcroft** [comment]
Ognian, your pre-built 64 bit binary runs well here, output:

```
$ sudo ./sdmon /dev/mmcblk0
{
"version": "v0.3.2-3 (a04b618) arm64",
"date": "2022-04-14T08:27:15.000Z",
"device":"/dev/mmcblk0",
"signature":"0x44 0x53",
"SanDisk":"true",
"manufactureYYMMDD": "211122",
"healthStatusPercentUsed": 1,
"featureRevision": "0x1f",
"generationIdentifier": 5,
"productString": "SanDisk                         ",
"success":true
}

```

**Comment by Ognian** [comment]
Looks like I can close this issue now...

**Comment by glynhudson** [comment]
> I have now added the SanDisk way into the code. A Development release is build and available. on 32bit raspberry pi os you can install it via
> 
> ```
> curl -L https://github.com/Ognian/sdmon/releases/download/latest/sdmon-armv7.tar.gz | tar zxf - 
> ```
> 
> on 64 bit raspberry pi os use
> 
> ```
> curl -L https://github.com/Ognian/sdmon/releases/download/latest/sdmon-arm64.tar.gz | tar zxf - 
> ```
> 
> sdmon needs no command line flags, it first tries the SanDisk way. If there is a signature different from 0xffff or 0x0000 it prints the info. SanDisk: true is set if it is a SanDisk signature, so that you can be sure that the info is correct. If signature was 0xffff or 0x0000 the APACER way is tried.
> 
> I have tested with the APACER cards where it works. I don't have SanDisk Industrial Cards to test. @glynhudson please could you test the 32 bit version with SanDisk and paste here the result so that I can put it as an example in the read.me @wjcroft please could you test the 64bit version too and also paste the output

Yup, works well for me:

```
{
"version": "v0.4.1-3 (63a79fd) armv7",
"date": "2022-08-11T02:05:07.000Z",
"device":"/dev/mmcblk0",
"addTime": "false",
"signature":"0x44 0x53",
"SanDisk":"true",
"manufactureYYMMDD": "210712",
"healthStatusPercentUsed": 1,
"featureRevision": "0x1f",
"generationIdentifier": 5,
"productString": "SanDisk                         ",
"success":true
}
```
