### ISSUE TITLE
No longer working with WD/Sandisk card

### ISSUE THREAD

**Issue by Silent-Hunter** [Ognian/sdmon#9]
I have a Raspberry Pi 4 8GB RAM version.

I purchased a Western Digital SDSDQED–064G-XI (Although it says Sandisk on the actual card I received). This program worked perfectly for the first day I had it. It's been about a month now, and it no longer works. I have no idea why.

```
{
"version": "v0.4.2 (63a79fd) arm64",
"date": "2023-04-20T21:17:02.000Z",
"device":"/dev/mmcblk0",
"addTime": "false",
"error":"device open failed"
}
```

**Comment by Silent-Hunter** [comment]
Wait, maybe it's because the Raspberry Pi OS now uses Linux kernel 6.1?

**Comment by krypton-x** [comment]
Here it is running fine with a kingston card and kernel 6.1.21. I can see the same error when the program is started without root privileges.

**Comment by Silent-Hunter** [comment]
That's what I get for filing a bug report while sick I guess! I forgot that you need to be root. It works fine.
